name: entao_http
description: Dart Http.
version: 3.1.1
repository: https://github.com/yangentao/entao_http
homepage: https://github.com/yangentao/entao_http

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  http_parser: ^4.1.2
  mime: ^2.0.0
#  async: ^2.13.0

  entao_lint: ^1.0.1
  println: ^1.0.4
  any_call: ^1.0.1
  entao_dutil: ^2.0.9
  entao_result: ^1.0.1


dev_dependencies:
  lints: any
  test: any
