name: entao_http
description: Dart Http.
version: 2.0.0
repository: https://github.com/yangentao/entao_http
homepage: https://github.com/yangentao/entao_http

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  println: ^1.0.0
  any_call: ^1.0.0
  entao_dutil: ^2.0.3
  #  entao_log: ^1.0.0
  http: ^1.5.0
  http_parser: ^4.1.2
  mime: ^2.0.0

dev_dependencies:
  lints: any
  test: any
