name: entao_http
description: Dart Http.
version: 3.2.3
repository: https://github.com/yangentao/entao_http
homepage: https://github.com/yangentao/entao_http

environment:
  sdk: ^3.7.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  #  async: ^2.13.0

  entao_lint: ^1.0.1
  entao_dutil: ^2.3.4
#  entao_result: ^1.0.4
  entao_log: ^2.0.1


dev_dependencies:
  println: ^1.0.4
  lints: any
  test: any
